Adamant-im/adamant-iOS

- Adamant/AppDelegate.swift
- Adamant/ServiceProtocols/ReachabilityMonitor.swift
- Adamant/Services/AdamantAccountService.swift
- Adamant/Services/AdamantReachability.swift
- Adamant/Services/DataProviders/AdamantChatsProvider.swift
Пофиксил мониторинг подключения к интернету.
Возможно (так и не удалось больше воспроизвести) баг был из-за рассинхрона двух мониторов, поэтому объединил их в один.
Нигде в приложении не имело значения, подключение идет через Wifi или через сотовую связь, поэтому мониторы можно спокойно объединять. К тому же это упрощает логику мониторинга интернета.
> Fixed incorrect connection label showing

- Adamant/Stories/Chats/ChatViewController+MessageKit.swift
Редкий баг при копировании сообщения - приложение крашится. Проявляется в новых сообщениях
Повторить так: отправить сообщение и попытаться быстро скопировать
> Copy crash bug

- Adamant/Stories/Chats/ChatViewController+MessageKit.swift
При обновлении статуса сообщения (после отправки) - чат скроллит вниз 2 раза (вместо 1). 
Причина: метод `sendMessage` возвращает `completion` два раза: один раз сразу и второй раз после отправки на сервер
> Scroll bug when update message status

- Adamant.xcodeproj/project.pbxproj
- Adamant/Assets/l18n/de.lproj/Localizable.strings
- Adamant/Assets/l18n/en.lproj/Localizable.strings
- Adamant/Assets/l18n/ru.lproj/Localizable.strings
- Adamant/Helpers/UIViewController+email.swift
- Adamant/ServiceProtocols/DialogService.swift
- Adamant/Services/AdamantDialogService.swift
- Adamant/Stories/Settings/AboutViewController.swift
- Adamant/Utilities/AdamantUtilities+extended.swift
Пофиксил краш при попытке отправить email в поддержку.
Теперь, если не получается показать экран с отправкой сообщения, вызывается диплинк, который обработается приложением для отправки эл. писем.
Также пофиксил получение названия модели устройства. Macbook показывался как iPad. Теперь все норм.
Единственное, оставил iPadOS. Способа достоверно получить версию MacOS на мультиплатформенных приложениях я так и не нашел. При получении сообщения нужно будет находить версию MacOS по [такому соответствию](https://stackoverflow.com/questions/63581114/mac-catalyst-version).
> Email sending fix

- Adamant.xcodeproj/project.pbxproj
- Adamant.xcworkspace/contents.xcworkspacedata
- Adamant/AppDelegate.swift
- Adamant/ServiceProtocols/DialogService.swift
- Adamant/Services/AdamantDialogService.swift
- Adamant/Services/AdamantPushNotificationsTokenService.swift
- Adamant/SwinjectDependencies.swift
- AdamantShared/Helpers/AdamantUtilities.swift
- NotificationServiceExtension/NotificationService.swift
- Podfile
- Podfile.lock
- PopupKit/.gitignore
- PopupKit/Package.swift
- PopupKit/README.md
- PopupKit/Sources/PopupKit/Implementation/Common/BlockingView.swift
- PopupKit/Sources/PopupKit/Implementation/Common/Blur.swift
- PopupKit/Sources/PopupKit/Implementation/Common/Constants.swift
- PopupKit/Sources/PopupKit/Implementation/Common/Extensions.swift
- PopupKit/Sources/PopupKit/Implementation/Common/HashableAction.swift
- PopupKit/Sources/PopupKit/Implementation/Common/TransparentWindow.swift
- PopupKit/Sources/PopupKit/Implementation/Common/View+BackgroundInteraction.swift
- PopupKit/Sources/PopupKit/Implementation/Models/AlertModel.swift
- PopupKit/Sources/PopupKit/Implementation/Models/NotificationModel.swift
- PopupKit/Sources/PopupKit/Implementation/Models/PopupCoordinatorModel.swift
- PopupKit/Sources/PopupKit/Implementation/Services/AutoDismissManager.swift
- PopupKit/Sources/PopupKit/Implementation/Views/AlertView.swift
- PopupKit/Sources/PopupKit/Implementation/Views/NotificationView.swift
- PopupKit/Sources/PopupKit/Implementation/Views/PopupCoordinatorView.swift
- PopupKit/Sources/PopupKit/Implementation/Views/ToastView.swift
- PopupKit/Sources/PopupKit/PopupManager.swift
Убрал библиотеку `FTIndicator`. Вместо нее написал наш вариант, который работает с macos. `FTIndicator` криво работала с macos, так как не было учтено возможности изменения размеров экрана.
В `PopupKit` сделал отдельный `UIWindow`, и в рамках него уже показываю попапы, чтобы не зависеть от переключающихся окошек в приложении. Написал библу на SwiftUI, поэтому поднял версию приложения до iOS 15
> Macos popups fix

- Adamant/AppDelegate.swift
- Adamant/ServiceProtocols/DataProviders/ChatsProvider.swift
- Adamant/ServiceProtocols/DataProviders/TransfersProvider.swift
- Adamant/Services/AdamantAccountService.swift
- Adamant/Services/AdamantAddressBookService.swift
- Adamant/Services/AdamantCurrencyInfoService.swift
- Adamant/Services/AdamantHealthCheckService.swift
- Adamant/Services/AdamantNodesSource.swift
- Adamant/Services/AdamantNotificationService.swift
- Adamant/Services/ApiService/AdamantApiService.swift
- Adamant/Services/DataProviders/AdamantAccountsProvider.swift
- Adamant/Services/DataProviders/AdamantChatTransactionService.swift
- Adamant/Services/DataProviders/AdamantChatsProvider+backgroundFetch.swift
- Adamant/Services/DataProviders/AdamantChatsProvider.swift
- Adamant/Services/DataProviders/AdamantTransfersProvider+backgroundFetch.swift
- Adamant/Services/DataProviders/AdamantTransfersProvider.swift
- Adamant/Services/SocketService/AdamantSocketService.swift
- Adamant/SwinjectDependencies.swift
- Adamant/Wallets/Adamant/AdmWalletService+RichMessageProvider.swift
- Adamant/Wallets/Adamant/AdmWalletService.swift
- Adamant/Wallets/ERC20/ERC20WalletService+RichMessageProvider.swift
- Adamant/Wallets/ERC20/ERC20WalletService.swift
- Adamant/Wallets/Ethereum/EthWalletService+RichMessageProvider.swift
- Adamant/Wallets/Ethereum/EthWalletService.swift
- AdamantShared/Models/AccountServiceStoreKey.swift
- AdamantTests/AdamantHealthCheckServiceTests.swift
- AdamantTests/FeeTests.swift
- AdamantTests/Stubs/ApiServiceStub.swift
- NotificationServiceExtension/NotificationService.swift
Пофиксил креш при background fetch.
Проблема была в том, что в `AdamantNodesSource` не добавлялась нужная зависимость.
Чтобы исключить такие проблемы в будущем, сделал рефакторинг:
1. Убрал force unwrap зависимостей в сервисах из DI (везде пока решил не убирать, много переписывать нужно)
2. Убрал отдельную регистрацию сервисов для бэкграунда. Swinject устроен так, что сервисы создаются при первой попытке получить доступ к ним. Поэтому ничего лишнего создаваться в бэкграунде не будет.
> Fixed background fetch crash

- Adamant/AppDelegate.swift
- Adamant/Assets/l18n/de.lproj/Localizable.strings
- Adamant/Assets/l18n/en.lproj/Localizable.strings
- Adamant/Assets/l18n/ru.lproj/Localizable.strings
- Adamant/ServiceProtocols/NotificationsService.swift
- Adamant/Services/AdamantNotificationService.swift
- Adamant/Services/AdamantPushNotificationsTokenService.swift
- Adamant/Stories/Chats/ChatListViewController.swift
- Adamant/Stories/Settings/NotificationsViewController.swift
- Adamant/Stories/Settings/SecurityViewController+notifications.swift
1. Пуши могли работать и без входа в аккаунт. Для этого на маке надо отключить сохранение акка, находясь на экране настройки уведомлений, а потом включить уведомления заново. Затем просто закрыть приложение. Пофиксил это.
2. Пофиксил сброс экранов на маке при выходе из акка.
3. Если зайти в приложение через пуш и попасть в чат, а затем выйти и зайти обратно в акк, при входе будет переброс в чат из пуша, по которому был запуск приложения. Исправил это.
> Fixed pushes working without account

- Adamant/Wallets/Bitcoin/BtcWalletService+Send.swift
- BitcoinKit/Sources/BitcoinKit/Core/Keys/Address.swift
- BitcoinKit/Sources/BitcoinKit/Messages/Transaction.swift
- BitcoinKit/Sources/BitcoinKit/Scripts/Script.swift
Добавил возможность создания `pay-to-script-hash`. Раньше для всех типов адресов создавались `pay-to-pubkey-hash` транзакции.
> Fixed sending btc transactions by pay-to-script-hash method

- Adamant/CoreData/Chatroom+CoreDataClass.swift
- Adamant/CoreData/Chatroom+CoreDataProperties.swift
- Adamant/Services/DataProviders/AdamantTransfersProvider.swift
- Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
- Adamant/Stories/ChatsList/ChatListViewController.swift
- Adamant/Stories/ChatsList/ChatsRoutes.swift
- Adamant/Stories/ChatsList/SearchResultsViewController.swift
1. Chat list: Chats where only income direct ADM payments are always unread
2. New and then seen messages sometimes shown unread
3. Chat list: when you use search, all contacts are without names, shown with ADM addresses
> [trello.com/c/P1bM0HMm] Chat list fixes

- Adamant.xcodeproj/project.pbxproj
- Adamant/Stories/Chat/View/ChatViewController.swift
- Adamant/Stories/Chat/View/Subviews/ChatMessagesCollection.swift
- Adamant/Stories/Chat/View/Subviews/ChatRefreshMock.swift
1. Если во время докрутки ленты после скролла начать скрывать клавиатуру, лента будет крутиться в 2 раза быстрее чем нужно. Пофиксил это.
2. Если начать скрывать клавиатуру при нахождении позиции скролла в самом верху, она отпружинит без анимации. Пофиксил это. Проблема была из-за MessageKit. Все работает нормально только при добавлении `UIRefreshControl`,  поэтому добавил мок для `UIRefreshControl` (`ChatRefreshMock`)
> [https://trello.com/c/7Yjrwi9r] Fixed chats collection layout

- Adamant/Services/AdamantNodesSource.swift
- Adamant/Services/ApiService/AdamantApiService.swift
- Adamant/Services/DataProviders/AdamantChatsProvider.swift
- Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
- AdamantShared/Models/Node.swift
Проблема была в слишком частом шифровании нод для сохранения в хранилище.
Решил так:
1. При неудачном запросе делаю `health check` не при каждом неудачном запросе на ноду, а только в конце.
2. Сделал проверку перед сохранением нод в хранилище.
Также исправил отправку повторного запроса на получение сообщений.
> [trello.com/c/IsInyuZJ] Health chech lags fix

- Adamant.xcodeproj/project.pbxproj
- Adamant/Models/TransactionStatus.swift
- Adamant/ServiceProtocols/RichMessageProviderWithStatusCheck/RichMessageProviderWithStatusCheck+Extension.swift
- Adamant/Services/RichTransactionStatusService/AdamantRichTransactionStatusService.swift
- Adamant/Services/RichTransactionStatusService/RichTransactionStatusPublisher.swift
- Adamant/Services/RichTransactionStatusService/RichTransactionStatusSubscription.swift
- Adamant/Stories/Chat/View/ChatViewController.swift
- Adamant/Stories/Chat/View/Managers/ChatDataSourceManager.swift
- Adamant/Stories/Chat/View/Subviews/ChatMessagesCollection.swift
- Adamant/Stories/Chat/View/Subviews/ChatModelView.swift
- Adamant/Stories/Chat/View/Subviews/ChatTransaction/ChatTransactionCellSizeCalculator.swift
- Adamant/Stories/Chat/View/Subviews/ChatTransaction/Container/ChatTransactionContainerView+Model.swift
- Adamant/Stories/Chat/View/Subviews/ChatTransaction/Container/ChatTransactionContainerView.swift
- Adamant/Stories/Chat/ViewModel/ChatMessageFactory.swift
- Adamant/Stories/Chat/ViewModel/Models/ChatMessage.swift
- Adamant/Wallets/Bitcoin/BtcWalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/Dash/DashWalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/Doge/DogeWalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/ERC20/ERC20WalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/ERC20/ERC20WalletService.swift
- Adamant/Wallets/Ethereum/EthWalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/Lisk/LskWalletService+RichMessageProviderWithStatusCheck.swift
- Adamant/Wallets/Lisk/LskWalletService.swift
- AdamantShared/Helpers/CollectionUtilites.swift
- LiskKit/Sources/Core/APIError.swift
1. Обработка статусов, когда нет интернета
2. Фикс установки `failed` статуса. Теперь он устанавливается после всех проваленных `oldPendingAttempts`
3. Пофиксил ленту. При слишком частых обновлениях контента она пропускала обновления для некоторых ячеек.
Теперь сделал так, что ячейки непосредственно подписываются на вью модель. Так обновления контента не пропускаются
> [trello.com/c/wEE12i1g] txFetch fix

- Adamant.xcodeproj/project.pbxproj
- Adamant/AppDelegate.swift
- Adamant/Stories/Chat/View/Managers/ChatLayoutManager.swift
- Adamant/Stories/Chat/View/Managers/FixedTextMessageSizeCalculator.swift
1. Пофиксил открытие чата по пушу в macos
2. На маке MessageKit иногда неправильно рисует ячейку сообщения, последнее слово пропадает. Пофиксил это.
> [trello.com/c/C8MNrgFw] Small macos fixes

- Adamant/Wallets/Lisk/LskTransactionsViewController.swift
- Adamant/Wallets/Lisk/LskWalletService+RichMessageProviderWithStatusCheck.swift
- LiskKit/Sources/API/Service/Models/ServiceTransactionModel.swift
- LiskKit/Sources/API/Transactions/Models/TransactionModel.swift
Сделал поля `block` и `height` необязательными. Они не приходят, если транзакция еще не подтверждена
> [trello.com/c/wEE12i1g] Unconfirmed transactions processing fix

- Adamant/ServiceProtocols/RichMessageProviderWithStatusCheck/RichMessageProviderWithStatusCheck+Extension.swift
- AdamantShared/Assets/l18n/de.lproj/Localizable.strings
- AdamantShared/Assets/l18n/ru.lproj/Localizable.strings
The problem is that the transaction was sent before the message, so it is not included in the segment `messageDate...end` , where `end` is `messageDate + consistencyMaxTime`
Solution: check the difference between `messageDate` and `txDate` is not bigger than `consistencyMaxTime`
> [trello.com/c/FZGCNq57] Fixed inconsistent status

- Adamant.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Adamant/Wallets/TransferViewControllerBase.swift
I couldn't reproduce bug but it's 90% caused by infinite recursion in this place. I haven't found any reason to reload form on cell update. Update form on cell value change only is enough.
> [trello.com/c/QcsLw1NJ] Hang on transfer fix

- Adamant/Services/AdamantVisibleWalletsService.swift
The algorithm was crashing in some situations when previously visible by default coins are no longer visible by default.
Example:
1. Make WOO visible by default in adamant-wallets
2. Replace WOO with ADM
3. Remove its visibility by default in adamant-wallets
> [trello.com/c/zUXIwW2y] Fixed a crash on wallets sorting

- Adamant/Modules/Wallets/Adamant/AdmWalletService.swift
The problem was that the wallet collection was being updated every 15 seconds. I believe that the data should only be updated if a wallet was previously uninitialized and then became initialized, or if its balance changed.
> [trello.com/c/pOZzbfOy] fixed bug: coin carousel scroll drop

- Adamant.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Adamant/Modules/Wallets/Doge/DogeWalletService+Send.swift
- Adamant/Services/FilesNetworkManager/IPFSApiService.swift
- CommonKit/Package.swift
- CommonKit/Sources/CommonKit/Protocols/APICoreProtocol.swift
- CommonKit/Sources/CommonKit/Services/APICore.swift
> The property `timeoutIntervalForRequest` determines the request timeout interval for all tasks within sessions based on this configuration. The request timeout interval controls how long (in seconds) a task should wait for additional data to arrive before giving up. The timer associated with this value is reset whenever new data arrives. When the request timer reaches the specified interval without receiving any new data, it triggers a timeout.
>
It seems that the system receives additional data instantly if it's an internal error and for some reason doesn't finish the request.
So I made the decision to use `timeoutIntervalForResource` that works for the entire request. But now it has different values for file requests and other common requests.
> [trello.com/c/Xj60TSNy] Stuck requests fix

- Adamant/Modules/Chat/View/ChatViewController.swift
- FilesPickerKit/Sources/FilesPickerKit/Pickers/DocumentInteractionService.swift
The problem was because a new pack of images could be presenting before complete closing of the previous one (it's possible after swiping). It led to unexpected behaviour because the service wasn't made to process a few packs simultaneously
> [trello.com/c/mCIOWeDH] Fixed file presenting

- Adamant/Modules/Wallets/ERC20/ERC20WalletService.swift
- CommonKit/Sources/CommonKit/Services/HealthCheck/BlockchainHealthCheckWrapper.swift
- CommonKit/Sources/CommonKit/Services/HealthCheck/HealthCheckWrapper.swift
1. Fixed extra ERC20 balance requests. All invisible wallets were requesting their balances just like the visible wallets.
2. It seems sometimes network requests still fail on entering background or returning to the active state. So I forcefully kill health check requests on entering background now to avoid false statuses.
> [trello.com/c/AmlmMsUi] Network layer fixes

- Adamant/Modules/Wallets/WalletViewControllerBase.swift
`.cellUpdate` from 141 line was overwritten in 158 line. So, code from line 141 is useless, we can delete it. But it was not the only reason caused bug.
Now height of balance cell is calculated based on current row ViewModel: `$0.cell.height = { row.value?.fiat != nil ? BalanceTableViewCell.fullHeight : BalanceTableViewCell.compactHeight }`.
According to docs, to update cell height (not the content), we should call `updateCell` just before `reload` call. Without `reload` call height of cell will not be updated
> [trello.com/c/ciHCs1De]: fix not updating row height after balance change

- Adamant/Modules/Wallets/Bitcoin/BtcWalletService.swift
- Adamant/Modules/Wallets/Dash/DashWalletService.swift
- Adamant/Modules/Wallets/Doge/DogeWalletService.swift
- Adamant/Modules/Wallets/Ethereum/EthWalletService.swift
- Adamant/Modules/Wallets/Klayr/WalletService/KlyWalletService.swift
- Adamant/Services/AdamantAddressBookService.swift
- CommonKit/Sources/CommonKit/Models/KVSValueModel.swift
- CommonKit/Sources/CommonKit/Protocols/AdamantApiServiceProtocol.swift
- CommonKit/Sources/CommonKit/Services/ApiService/AdamantApi+States.swift
**Before:**
A blockchain address is passed as a parameter, the keypair is being received just before sending the address to the KVS. It can cause inconsistency and bugs such as saving a blockchain address from an old account to a new account's storage.
**After:**
A model, containing all the required data, is generated on wallet initialization. Then it's passed to methods to store data in KVS. No more inconsistency.
> [trello.com/c/etjLStc6] KVS-related code refactoring
