Adamant/Services/ApiService/AdamantApiService.swift
Adamant/SwinjectDependencies.swift

Add servers list
Add random server selecting
Add server status check

Servers list

---

Adamant/Stories/Chats/ChatListViewController.swift
Adamant/Stories/Chats/ChatViewController+MessageKit.swift
Adamant/Stories/Transactions/TransactionDetailsViewController.swift
Adamant/Stories/Transactions/TransactionsViewController.swift
Adamant/Utilities/AdamantUtilities.swift
Podfile

New humanized date formatting for chat messegase and transactions

New date formatting

---

Adamant/Assets/l18n/de.lproj/Localizable.strings

I will look at the translation in the app to correct some words later (I need to see the context)

German translation added

---

Adamant/Assets/l18n/de.lproj/Localizable.stringsdict

Must see how it looks in the app but I hope I translated right strings :)

Updated german strings

---

Adamant/Wallets/Ethereum/EthWalletService.swift

fix eth wallet path

---

Adamant/Assets/l18n/de.lproj/Localizable.strings
Adamant/Assets/l18n/en.lproj/Localizable.strings
Adamant/Assets/l18n/ru.lproj/Localizable.strings
Adamant/Stories/Chats/ChatViewController+MessageKit.swift
Adamant/Stories/Chats/ChatViewController.swift

Add handler for links in chat messages
Fix vertical alignment in text field
Move "send" button outside of text field

Chat bugfix

---

Adamant.xcodeproj/project.pbxproj
Adamant/Services/AdamantDialogService.swift
Adamant/Services/AdamantNotificationService.swift
Adamant/Services/DataProviders/AdamantAccountsProvider.swift
Adamant/Stories/Chats/ChatListViewController.swift
Adamant/Stories/Chats/ChatViewController.swift
Adamant/Stories/Chats/NewChatViewController.swift
Adamant/Stories/Chats/SearchResultsViewController.swift
Adamant/Stories/Delegates/DelegatesListViewController.swift
Adamant/Stories/Login/LoginViewController+QR.swift
Adamant/Stories/NodesEditor/NodeEditorViewController.swift
Adamant/Wallets/Adamant/AdmTransactionsViewController.swift
Adamant/Wallets/ERC20/ERC20TransactionsViewController.swift
Adamant/Wallets/Ethereum/EthTransactionsViewController.swift
Adamant/Wallets/TransferViewControllerBase+Alert.swift
Adamant/Wallets/TransferViewControllerBase+QR.swift
Adamant/Wallets/TransferViewControllerBase.swift
AdamantShared/Helpers/GCDUtilites.swift

UI methods were called not on main thread. Due to it app crashed after node testing in nodes list
Also some methods access was changed to `private` because its are used in `NodeEditorViewController` only

Fixed node test crash

---

Adamant.xcodeproj/project.pbxproj
Adamant/Models/AdamantAccount.swift
Adamant/ServiceProtocols/AccountService.swift
Adamant/ServiceProtocols/ApiService.swift
Adamant/Services/AdamantAccountService.swift
Adamant/Services/ApiService/AdamantApi+Accounts.swift
Adamant/Stories/Login/LoginViewController.swift
Adamant/Utilities/AddressGenerator.swift
AdamantTests/AddressGeneratorTests.swift

Добавил генерацию адреса.
Когда запрашиваем аккаунт по публичному ключу и приходит ошибка `Account not found`, теперь создаем пустой аккаунт и сами генерируем для него адрес.
Также убрал все методы для создания аккаунтов, потому что больше они не нужны.

Added address generation

---

Adamant.xcodeproj/project.pbxproj
Adamant/Services/AdamantHealthCheckService.swift
Adamant/Services/ApiService/AdamantApi+Delegates.swift
Adamant/SharedViews/LoadingView.swift
Adamant/Stories/Chats/ChatViewController.swift
Adamant/Stories/Delegates/DelegatesListViewController.swift

1. Пофиксил показ делегатов при отсутствии аккаунта на ноде.
2. Добавил экран загрузки на экран делегатов
3. Починил еще креш при health check

Delegates screen fix

---

Adamant/Assets/l18n/de.lproj/Localizable.strings

German localization fix

---

Adamant.xcodeproj/project.pbxproj
Adamant/Services/AdamantHealthCheckService.swift
AdamantTests/AdamantHealthCheckServiceTests.swift

Added health check tests

---

Adamant/Services/ApiService/AdamantApi+Chats.swift
Adamant/Services/ApiService/AdamantApiService.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift

Пофиксил креш при повторном запросе сообщений в случае ошибки

Fixed crash on chats reconnect

---

AdamantShared/Models/Node.swift

Исправлено подключение сокетов к https нодам

Fix sockets connection on https nodes

---

Adamant/Stories/Chats/NewChatViewController.swift
Adamant/Wallets/TransferViewControllerBase+QR.swift

Фикс краша при сканировании QR кода

Fixed QR camera crash on first launch

---

Adamant.xcodeproj/project.pbxproj
Adamant/Stories/NodesEditor/NodesListViewController.swift
AdamantShared/Helpers/CollectionUtilites.swift

Когда все ноды офлайн, был баг при сбрасывании их. Список не сбрасывался. Пофиксил это.

Fixed nodes resetting

---

Adamant.xcodeproj/project.pbxproj

Version 2.7.0

---

Adamant/Stories/Account/AccountViewController.swift
Adamant/Stories/Account/WalletCollectionViewCell.swift
Adamant/Stories/Account/WalletPagingItem.swift
Adamant/Stories/Chats/ComplexTransferViewController.swift
Adamant/Wallets/Adamant/AdmWalletService.swift
Adamant/Wallets/Dash/DashWalletService.swift
Adamant/Wallets/Doge/DogeWalletService.swift
Adamant/Wallets/ERC20/ERC20WalletService.swift
Adamant/Wallets/Ethereum/EthWalletService.swift
Adamant/Wallets/Lisk/LskWalletService.swift
Adamant/Wallets/WalletService.swift

Отображение сети монет для ERC20: USDS, BNB.

Show coin network

---

Adamant/Stories/Account/AccountHeader.xib
Adamant/Stories/Account/WalletCollectionViewCell.xib
Adamant/Wallets/ERC20/ERC20TransferViewController.swift
Adamant/Wallets/ERC20/ERC20WalletService+RichMessageProvider.swift
Adamant/Wallets/ERC20/ERC20WalletViewController.swift

Доделал показ сети ERC20:  на экране Send ... (и на главном экране), в чате у полученных и отправленных транзакций. Изменил паддинг на экране отправки из чата

Show coin network ERC20 in chat, wallet

---

AdamantShared/Helpers/Decimal+adamant.swift

Фикс десятичной точности при отправлении коинов (отправляем 0.33 - отправляется 0.2999)

Fixed bug with loss of decimal precision

---

Adamant/Services/DataProviders/AdamantChatsProvider.swift

Фикс дубликатов сообщений. Исправлено 2 сценария: 
1. При плохом инет соединении, при отправке сообщения и парада звезд возможен был вариант: 
- ответ от запроса по отправке сообщения задерживался и показанное в чате сообщение было без ИД (его берем из ответа запроса)
- приходило время ручного запроса сообщений (каждые 10 сек)
в результате из-за ручного запроса сообщений добавлялось "новое" сообщение (тк ид отправленного сообщения не был присвоен и не удалось найти похоже в бд), а позже приходил ответ от самого запроса отправки сообщения. В результате имеем 2 одинаковых сообщения
2. Загрузка первых 5 чатов по умолчанию делалась параллельно добавлению в бд всех чатов, от того последнее видимое сообщение добавлялось 2 раза у таких чатов

Fixed duplicate messages

---

Adamant/Stories/Account/WalletCollectionViewCell.xib
Adamant/Wallets/Adamant/AdmWalletViewController.swift
Adamant/Wallets/Dash/DashWalletViewController.swift
Adamant/Wallets/Doge/DogeWalletViewController.swift
Adamant/Wallets/ERC20/ERC20WalletService+RichMessageProvider.swift
Adamant/Wallets/ERC20/ERC20WalletViewController.swift
Adamant/Wallets/Ethereum/EthWalletViewController.swift
Adamant/Wallets/Lisk/LskWalletViewController.swift
Adamant/Wallets/WalletViewControllerBase.swift

Небольшие изменения по отображению ERC20 коинов в чате и в главном экране

Erc20 coins design

---

Adamant/Stories/Chats/ChatViewController.swift
Adamant/Stories/NodesEditor/NodeEditorViewController.swift

1. Теперь при нажатии на enter, если в поле ввода на стоит курсор, курсор ставится.
2. Пофиксил пропажу курсора при control + enter.
3. Дофиксил съезд нижнего сообщения под поле для ввода. Осталась проблема только на айпаде, но там можно проскроллить.

Fixed keyboard processing

---

Adamant/Services/DataProviders/AdamantChatsProvider.swift
Adamant/Stories/Chats/ChatViewController+MessageKit.swift

Macos crashes fix

---

Adamant/AppDelegate.swift
Adamant/Helpers/MacOSDeterminer.swift
Adamant/ServiceProtocols/DialogService.swift
Adamant/Services/AdamantAuthentication.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift
Adamant/Stories/Account/AccountViewController.swift
Adamant/Stories/Chats/ChatListViewController.swift
Adamant/Stories/Chats/ChatViewController.swift
Adamant/Stories/Chats/ComplexTransferViewController.swift
Adamant/Stories/Chats/HeaderReusableView.swift
Adamant/Stories/Chats/NewChatViewController.swift
Adamant/Stories/Chats/SearchResultsViewController.swift
Adamant/Stories/Delegates/DelegatesListViewController.swift
Adamant/Stories/Login/LoginViewController+QR.swift
Adamant/Stories/NodesEditor/NodesListViewController.swift
Adamant/Stories/Settings/AboutViewController.swift
Adamant/Stories/Settings/NotificationsViewController.swift
Adamant/Stories/Settings/PKGeneratorViewController.swift
Adamant/Stories/Settings/QRGeneratorViewController.swift
Adamant/Wallets/TransactionDetailsViewControllerBase.swift
Adamant/Wallets/TransactionsListViewControllerBase.swift
Adamant/Wallets/TransferViewControllerBase+QR.swift
Adamant/Wallets/WalletViewControllerBase.swift
AdamantShared/Helpers/UIColor+adamant.swift

1.  Добавил выделение строки с чатом при переходе в чат через пуш
2. Пофиксил креш из-за попытки одновременно вписать данные по одному адресу с разных потоков
3. Убрал все лишние проверки на версии iOS

Added chat selection on push tap

---

Adamant.xcodeproj/project.pbxproj
Adamant/CoreData/ChatTransaction+CoreDataClass.swift
Adamant/ServiceProtocols/DataProviders/ChatsProvider.swift
Adamant/ServiceProtocols/RichTransactionStatusService.swift
Adamant/Services/AdamantRichTransactionStatusService.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift
Adamant/Stories/Chat/View/ChatViewController.swift
Adamant/Stories/Chat/View/Managers/ChatDataSourceManager.swift
Adamant/Stories/Chat/View/Managers/ChatDisplayManager.swift
Adamant/Stories/Chat/View/Managers/ChatLayoutManager.swift
Adamant/Stories/Chat/View/Subviews/ChatMessagesCollection.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/ChatTransactionCellSizeCalculator.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/Container/ChatTransactionContainerView+Model.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/Container/ChatTransactionContainerView.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/Content/ChatTransactionContentView+Model.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/Content/ChatTransactionContentView.swift
Adamant/Stories/Chat/View/Subviews/MessageCollectionViewCell+Extension.swift
Adamant/Stories/Chat/ViewModel/ChatMessageFactory.swift
Adamant/Stories/Chat/ViewModel/ChatMessagesListService.swift
Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
Adamant/Stories/Chat/ViewModel/Models/ChatMessage.swift
Adamant/Stories/Chat/ViewModel/Models/ChatMessageBackgroundColor.swift
AdamantShared/Models/ComparableAction.swift

1. Парсинг markdown вызывался при каждом скролле. Исправил это.
2. Вынес создание моделей в фоновый поток, чтобы разгрузить основной поток
Теперь почти все данные для отображения лежат именно в моделях и генерируются в фоновом потоке.

[trello.com/c/qdDT0Ic1] Chat optimization

---

Adamant.xcodeproj/project.pbxproj
Adamant/Stories/Chat/View/Subviews/ChatMessagesCollection.swift
Adamant/Stories/Chat/View/Subviews/ChatTransaction/Container/ChatTransactionContainerView+Model.swift
Adamant/Stories/Chat/ViewModel/ChatMessagesListFactory.swift
Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
Adamant/Stories/Chat/ViewModel/Models/ChatMessage.swift

1. Фикс обновления статуса btc транзакции при нажатии на иконку статуса
2. Фикс морганий при скролле в самый низ

[trello.com/c/qdDT0Ic1] Small chat fixes

---

Adamant/Wallets/ERC20/ERC20WalletService.swift

```
/// Subtract `other` from this integer in place.
/// `other` is shifted `shift` digits to the left before being subtracted.
///
/// - Requires: self >= other * 2^shift
/// - Complexity: O(count)
public mutating func subtract(_ other: BigUInt, shiftedBy shift: Int = 0) {
let overflow = subtractReportingOverflow(other, shiftedBy: shift)
precondition(!overflow)
}
```

[trello.com/c/TbBMgk7o] ERC20 confirmations calculating crash fix

---

PopupKit/Sources/PopupKit/Implementation/Services/AutoDismissManager.swift
PopupKit/Sources/PopupKit/PopupManager.swift

Fix CPU after Lisk transaction sending

[trello.com/c/0YfvDm71] Fix CPU after Lisk transaction sending

---

Adamant.xcodeproj/project.pbxproj
Adamant/ServiceProtocols/DataProviders/ChatsProvider.swift
Adamant/ServiceProtocols/Router.swift
Adamant/Services/AdamantRichTransactionStatusService.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift
Adamant/Services/SwinjectedRouter.swift
Adamant/Stories/Chat/ChatFactory.swift
Adamant/Stories/Chat/View/ChatViewController.swift
Adamant/Stories/Chat/View/Managers/ChatCellManager.swift
Adamant/Stories/Chat/View/Managers/ChatDataSourceManager.swift
Adamant/Stories/Chat/View/Managers/ChatDialogManager.swift
Adamant/Stories/Chat/View/Managers/ChatDisplayManager.swift
Adamant/Stories/Chat/View/Managers/ChatInputBarManager.swift
Adamant/Stories/Chat/View/Managers/ChatLayoutManager.swift
Adamant/Stories/Chat/View/Subviews/ChatMessagesCollection.swift
Adamant/Stories/Chat/ViewModel/ChatCacheService.swift
Adamant/Stories/Chat/ViewModel/ChatMessagesListFactory.swift
Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
Adamant/SwinjectDependencies.swift

После внедрения async/await экран чата грузился еще дольше (около 1 секунды) + были промаргивания из-за того, что позиция скролла получалась асинхронно и устанавливалась после отображения сообщений.
Пофиксил это, сделав кеш моделей сообщений + перевел модуль чатов на @MainActor

[trello.com/c/ECFjYCYq] Chats fix

---

Adamant.xcodeproj/project.pbxproj

Release notes:
- Welcome Adelina, an artificial intelligence (AI) chatbot based on ChatGPT
- Bet on Bitcoin price chat removed

[trello.com/c/CZkfBu8t] Release 2.9.0

---

Adamant/Wallets/Bitcoin/BtcTransferViewController.swift
Adamant/Wallets/Bitcoin/BtcWalletService+Send.swift
Adamant/Wallets/Dash/DashTransferViewController.swift
Adamant/Wallets/Dash/DashWalletService+Send.swift
Adamant/Wallets/Doge/DogeTransferViewController.swift
Adamant/Wallets/Doge/DogeWalletService+Send.swift
Adamant/Wallets/ERC20/ERC20TransferViewController.swift
Adamant/Wallets/ERC20/ERC20WalletService+Send.swift
Adamant/Wallets/Ethereum/EthTransferViewController.swift
Adamant/Wallets/Ethereum/EthWalletService+Send.swift
Adamant/Wallets/Lisk/LskTransferViewController.swift
Adamant/Wallets/Lisk/LskWalletService+Send.swift
Adamant/Wallets/WalletService.swift

Сделать как в adamant-im. Сначала отправляем ADM-сообщение с передачей крипты (для передачи в чате) с айдишником транзакции, потом переходим к деталям и отправляем транзакцию коина, она будет в статусе Pending до прояснения.

[trello.com/c/wEE12i1g] Sending transaction after recepient notifying

---

Adamant.xcodeproj/project.pbxproj
Adamant.xcworkspace/xcshareddata/swiftpm/Package.resolved
Adamant/Stories/ChatsList/ChatListViewController.swift
AdamantShared/Helpers/UIHelpers/UIViewController+KeyboardSafeArea.swift

Пофиксил отслеживание клавиатуры на списке чатов.
Заменил инструмент от `MessageKit` на кастомный

[trello.com/c/DC9yyPea] Fixed keyboard observing

---

Adamant/Services/AdamantDialogService.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift

Fixed messages sending errors processing

[trello.com/c/IsInyuZJ] Fixed messages sending errors processing

---

Adamant.xcodeproj/project.pbxproj
Adamant/ServiceProtocols/DialogService.swift
Adamant/Services/AdamantDialogService.swift
Adamant/Wallets/WalletService.swift
Podfile
Podfile.lock
PopupKit/Sources/PopupKit/Implementation/Common/HashableAction.swift
PopupKit/Sources/PopupKit/Implementation/Models/AdvancedAlertModel.swift
PopupKit/Sources/PopupKit/Implementation/Models/PopupCoordinatorModel.swift
PopupKit/Sources/PopupKit/Implementation/Views/AdvancedAlertView.swift
PopupKit/Sources/PopupKit/Implementation/Views/PopupCoordinatorView.swift
PopupKit/Sources/PopupKit/PopupManager.swift

1. Переписал exception попап на SwiftUI и добавил его в PopupKit
2. Встроил в общую систему с другими попапами, чтобы он не исчезал при смене экранов
3. Убрал старый вариант

[trello.com/c/CqIWGwix] New exception popup

---

Adamant/Services/DataProviders/AdamantChatsProvider.swift

Fixed getting all message transactions on startup

[trello.com/c/6oO4o0dR] Fixed getting all transactions on startup

---

Adamant/Services/DataProviders/AdamantChatsProvider.swift
Adamant/Stories/Chat/ViewModel/ChatCacheService.swift
Adamant/Stories/Chat/ViewModel/ChatViewModel.swift
Adamant/Stories/ChatsList/ChatListViewController.swift

Фикс рекурсии загрузки транзакций + другие правки, которые заметил

[trello.com/c/HeObh88U] Infinity loading fix

---

Adamant/Stories/Chat/View/ChatViewController.swift

Next time let's use `safe` when we access array items

[https://trello.com/c/CxcJke7p] MacOS crash fix

---

Adamant/ServiceProtocols/DialogService.swift
Adamant/Services/AdamantDialogService.swift
Adamant/Stories/Account/AccountViewController.swift
Adamant/Stories/Chat/View/Managers/ChatCellManager.swift
Adamant/Stories/Chat/View/Managers/ChatDialogManager.swift
Adamant/Stories/Chat/ViewModel/Models/ChatDialog.swift
Adamant/Stories/ChatsList/ChatListViewController.swift
Adamant/Stories/ChatsList/NewChatViewController.swift
Adamant/Stories/Login/LoginViewController+Pinpad.swift
Adamant/Stories/Login/LoginViewController+QR.swift
Adamant/Stories/NodesEditor/NodeEditorViewController.swift
Adamant/Stories/NodesEditor/NodesListViewController.swift
Adamant/Stories/Settings/NotificationsViewController.swift
Adamant/Stories/Settings/QRGeneratorViewController.swift
Adamant/Stories/Settings/SecurityViewController+notifications.swift
Adamant/Stories/Settings/VisibleWallets/VisibleWalletsViewController.swift
Adamant/Wallets/TransactionDetailsViewControllerBase.swift
Adamant/Wallets/TransferViewControllerBase+QR.swift
Adamant/Wallets/TransferViewControllerBase.swift
CommonKit/Sources/CommonKit/Helpers/UIHelpers/UIAlertController+Extension.swift

Made safe init for UIAlertController to avoid such type of crash in the future

[trello.com/c/MsAAd9np] Incorrect alert type crash fix

---

Adamant/Modules/Chat/View/Managers/ChatDataSourceManager.swift
Adamant/Modules/Chat/View/Managers/FixedTextMessageSizeCalculator.swift
Adamant/Modules/Chat/View/Subviews/ChatTransaction/ChatTransactionCell.swift
Adamant/Modules/Chat/ViewModel/ChatMessagesListFactory.swift

Added "Date" header in the chat from the day if it starts with a transfer

[trello.com/c/GcXhssF3] Fix: Date header in chat

---

Adamant/Modules/Wallets/TransferViewControllerBase.swift
CommonKit/Sources/CommonKit/Assets/Localization/de.lproj/Localizable.strings
CommonKit/Sources/CommonKit/Assets/Localization/en.lproj/Localizable.strings
CommonKit/Sources/CommonKit/Assets/Localization/ru.lproj/Localizable.strings
CommonKit/Sources/CommonKit/Assets/Localization/zh.lproj/Localizable.strings

Not enought money to send report ⟶ Not enough ADM to send in-chat transfer
Not enought tokens to vote. You need 50 ADM ⟶ Not enough ADM to pay the voting blockchain fee

[trello.com/c/lW8vh9sx] Fix localizations

---

Adamant.xcworkspace/xcshareddata/swiftpm/Package.resolved
Adamant/App/DI/AppAssembly.swift
Adamant/Modules/CoinsNodesList/ViewModel/CoinsNodesListViewModel.swift
Adamant/Modules/NodesEditor/NodesListViewController.swift
Adamant/Modules/Wallets/Doge/DogeWalletService+Send.swift
Adamant/Services/DataProviders/DefaultNodesProvider.swift
Adamant/Services/FilesNetworkManager/IPFSApiService.swift
CommonKit/Package.swift
CommonKit/Sources/CommonKit/ExtensionsTools/ExtensionsApiFactory.swift
CommonKit/Sources/CommonKit/Protocols/APICoreProtocol.swift
CommonKit/Sources/CommonKit/Protocols/NodesStorageProtocol.swift
CommonKit/Sources/CommonKit/Services/APICore.swift
CommonKit/Sources/CommonKit/Services/HealthCheck/HealthCheckWrapper.swift
CommonKit/Sources/CommonKit/Services/NodesStorage.swift

The problem was that after a reset the health check wrapper didn't recognize any changes and therefore didn't do a health check

[trello.com/c/sG2vnZbQ] Slow Health check fix

---

FilesPickerKit/Sources/FilesPickerKit/Helpers/FilesPickerKit.swift

Downgrade to the previous code (the current one was for Swift 6)

[trello.com/c/sNeeQGR9] Media sending failure fix

---

Adamant/Services/AdamantPushNotificationsTokenService.swift
CommonKit/Sources/CommonKit/Protocols/AdamantApiServiceProtocol.swift
CommonKit/Sources/CommonKit/Services/ApiService/AdamantApi+Chats.swift
CommonKit/Sources/CommonKit/Services/ApiService/AdamantApi+States.swift
CommonKit/Sources/CommonKit/Services/ApiService/AdamantApi+Transactions.swift
CommonKit/Sources/CommonKit/Services/ApiService/AdamantApi+Transfers.swift
CommonKit/Sources/CommonKit/Services/HealthCheck/HealthCheckWrapper.swift

Reverts Adamant-im/adamant-iOS#591
Needs more complete solution

Revert "[trello.com/c/2X9Nvf9m] HTTP Request adjustment"

---

CommonKit/Sources/CommonKit/Services/HealthCheck/HealthCheckWrapper.swift

Old algorithm:
1. Get the list of allowed nodes
2. Call them consequently unless some of them returns a successful response.
The old algo has a flaw. Each request can take up to 15-17 secs because of timeouts. In total it can take a few minutes of waiting. During this time the list of allowed nodes will be changed. But the algo will still be using the old list of allowed nodes.
New algorithm:
Repeat unless no more nodes left:
- Get the list of allowed nodes
- Remove the previous nodes from this list
- Make a request
- If there is an error, try again
So, on each request this algorithm uses the actual list of allowed nodes.

[trello.com/c/SLNfgog6] Health check algo fix

---

Adamant/Modules/Chat/View/ChatViewController.swift
Adamant/Modules/TransactionsStatusService/Services/TxStatusService.swift
Adamant/Modules/Wallets/Bitcoin/BtcWalletService.swift
Adamant/Modules/Wallets/Dash/DashWalletService.swift
Adamant/Modules/Wallets/Doge/DogeWalletService.swift
Adamant/Modules/Wallets/ERC20/ERC20WalletService.swift
Adamant/Modules/Wallets/Ethereum/EthWalletService.swift
Adamant/Modules/Wallets/Klayr/WalletService/KlyWalletService.swift
Adamant/Modules/Wallets/TransferViewControllerBase.swift
Adamant/Services/AdamantAccountService.swift
Adamant/Services/AdamantAddressBookService.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift
CommonKit/Sources/CommonKit/Helpers/Task+Extension.swift
pckg/AdvancedContextMenuKit/Sources/AdvancedContextMenuKit/AdvancedContextMenuManager.swift

1. No available nodes message fix
2. Balances invalidation timer pauses in background

[trello.com/c/9nKvz1hT] Wallet health check improvements testing fixes

---

Adamant/Helpers/Node+UI.swift
Adamant/Modules/CoinsNodesList/View/CoinsNodesListView+Row.swift
Adamant/Modules/CoinsNodesList/ViewModel/CoinsNodesListMapper.swift
Adamant/Modules/CoinsNodesList/ViewModel/CoinsNodesListState.swift
Adamant/Modules/NodesEditor/NodeCell/NodeCell+Model.swift
Adamant/Modules/NodesEditor/NodeCell/NodeCell.swift
Adamant/Modules/NodesEditor/NodesListViewController.swift
Adamant/SharedViews/CheckmarkRowView.swift
CommonKit/Sources/CommonKit/Services/NodesStorage.swift

1. UI adjustments 
2. Disabled nodes were shown as Sync after enabling

[trello.com/c/B6J21c0H] Fixes after testing

---

Adamant/App/AppDelegate.swift
BitcoinKit/Package.swift

This MR disables external keyboard support within the app.
Due to the fact that external keyboards may send the data over to proprietary servers, it is reasonable to disable the support for keyboard extensions (iOS).
|Before|After|
:-:|:-:

[trello.com/c/57u3CHwN] Disabled keyboard extensions within the app

---

Adamant/Modules/Wallets/Adamant/AdmWalletService+DynamicConstants.swift
Adamant/Modules/Wallets/Bitcoin/BtcWalletService+DynamicConstants.swift

New BTC explorer and info service alternative IP

[trello.com/c/jcTggeWE] adamant-wallets updates

---

Adamant/Modules/Chat/ViewModel/ChatViewModel.swift
Adamant/Modules/Wallets/Adamant/AdmWalletService+DynamicConstants.swift
Adamant/ServiceProtocols/DataProviders/ChatsProvider.swift
Adamant/Services/DataProviders/AdamantChatsProvider+fakeMessages.swift
Adamant/Services/DataProviders/AdamantChatsProvider.swift

Added a time correction. Presenting an error on message send failure. Refactoring

---

.githooks/commit-msg
scripts/init_hooks.sh

TO make it work just run 
`sh scripts/init_hooks`

[trello.com/c/rKj7beCB] Added commit-msg hook
